[package]
name = "oak_linux_boot_params"
version = "0.1.0"
authors = ["Andri Saar <andrisaar@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
bitflags = "2"
static_assertions = "1"
strum = { version = "0.28", default-features = false, features = ["derive"] }
zerocopy = { version = "0.8", features = ["derive"] }
